# Generated by Django 2.1.15 on 2020-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biospecimen',
            name='aliquot_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
